language: java

jdk: openjdk11

cache:
  directories:
  - "$HOME/.cache"

script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B

deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && ./mvnw deploy jib:build
